service: max-dev

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json

functions:
  hello:
    handler: handler.hello
