service: task1

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  environment:
    TABLE_NAME:
      Ref: UsersTable2 # reference for functions
    Get_Function: "getUser"

functions:
  logItemChanges:
    handler: handler.logItemChanges
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [UsersTable2, StreamArn]
    iamRoleStatementsName: logItemChangesRole #optional custom role name setting instead of the default generated one
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams       
        Resource: 
          - "Fn::GetAtt": [UsersTable2, Arn] # Fn::GetAtt: [ logicalNameOfResource, attributeName ] - this is for getting the Arn(Identifier) of the resource usersTable
  getUser:
    handler: handler.getItemFromDB
    name: getUser
    iamRoleStatementsName: getItemFromDBRole #optional custom role name setting instead of the default generated one
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:GetItem
        Resource: 
          - "Fn::GetAtt": [UsersTable2, Arn] # Fn::GetAtt: [ logicalNameOfResource, attributeName ] - this is for getting the Arn(Identifier) of the resource usersTable
      #events:
      #- http:
          #path: Hier route eintragen
          #method: GET
  putOrPost: 
    handler: handler.writeToDB
    iamRoleStatementsName: writeToDBRole #optional custom role name setting instead of the default generated one
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem  
          - dynamodb:Query
        Resource:
          - "Fn::GetAtt": [ UsersTable2, Arn ] # Fn::GetAtt: [ logicalNameOfResource, attributeName ] - this is for getting the Arn(Identifier) of the resource usersTable
      - Effect: "Allow"
        Action:
          - lambda:InvokeFunction
        Resource:
        #  - "*"
        #  - "Fn::GetAtt": [ GetUserLambdaFunction , Arn ]
           - !GetAtt GetUserLambdaFunction.Arn

  
resources: # CloudFormation template syntax from here on.
  Resources:
    UsersTable2: #must be same as TableName
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable2
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: N # N = All number types, also int or double are ok for example
          # - AttributeName: Name
          #   AttributeType: S # S for String
          # - AttributeName: Surname
          #   AttributeType: S   
        KeySchema:
          - AttributeName: ID
            KeyType: HASH   
          # - AttributeName: Name
          #   KeyType: RANGE
        # LocalSecondaryIndexes:
        # - IndexName: by-Surname
        #   KeySchema: 
        #   - AttributeName: ID
        #     KeyType: HASH
        #   - AttributeName: Surname
        #     KeyType: RANGE  
        #   Projection: 
        #     ProjectionType: ALL  
        # - IndexName: by-Name
        #   KeySchema: 
        #   - AttributeName: ID
        #     KeyType: HASH
        #   - AttributeName: Name
        #     KeyType: RANGE  
        #   Projection: 
        #     ProjectionType: ALL  
        StreamSpecification:
           StreamViewType: NEW_AND_OLD_IMAGES
        BillingMode: PAY_PER_REQUEST
       # ProvisionedThroughput:
        #  ReadCapacityUnits: 1
        #  WriteCapacityUnits: 1
plugins:
  - serverless-iam-roles-per-function
