service: task3-lukas

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  environment:
    Table_Name: ${file(./env.yml):Table_Name}
    GSI_Name: ${file(./env.yml):Index_Name}
    Partition_Key: ${file(./env.yml):Partition_Key} #email
    Sort_Key: ${file(./env.yml):Sort_Key} #birthday
    Get_Function: ${self:functions.read.name}
    Token_Index_Name: ${file(./env.yml):Token_Index_Name}

package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
    - data/**

functions:
  # User Functions
  read:
    handler: handler/read.read
    name: ${self:service}-${sls:stage}-read
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
        Resource:
          - "Fn::GetAtt": [ UsersTableLukas, Arn ]
    events:
      - http:
          path: ${file(./env.yml):UserGetInformation}
          method: get
          authorizer:
            identitySource: method.request.header.token
            type: token
            name: tokenAuthorizer

  create:
    handler: handler/create.create
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
          - "Fn::GetAtt": [ UsersTableLukas, Arn ]
      - Effect: "Allow"
        Action:
          - lambda:InvokeFunction
        Resource:
          - !GetAtt ReadLambdaFunction.Arn # shortcut to get arn, yaml syntax
    events:
      - http:
          path: ${file(./env.yml):UserRegisterPath}
          method: post

  update:
    handler: handler/update.update
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
          - "Fn::GetAtt": [ UsersTableLukas, Arn ]
      - Effect: "Allow"
        Action:
          - lambda:InvokeFunction
        Resource:
          - !GetAtt ReadLambdaFunction.Arn # shortcut to get arn, yaml syntax
    events:
      - http:
          path: ${file(./env.yml):UserUpdatePath}
          method: post
          authorizer:
            identitySource: method.request.header.token
            type: token
            name: tokenAuthorizer

  updatePrio:
    handler: handler/updatePrio.updatePrio
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
          - "Fn::GetAtt": [ UsersTableLukas, Arn ]
      - Effect: "Allow"
        Action:
          - lambda:InvokeFunction
        Resource:
          - !GetAtt ReadLambdaFunction.Arn # shortcut to get arn, yaml syntax

  delete:
    handler: handler/delete.delete
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DeleteItem
        Resource:
          - "Fn::GetAtt": [ UsersTableLukas, Arn ] # longer way to get the arn JSON like
      - Effect: "Allow"
        Action:
          - lambda:InvokeFunction
        Resource:
          - !GetAtt ReadLambdaFunction.Arn # shortcut to get arn, yaml syntax

  # Login in and out
  login:
    handler: handler/login.login
    events:
      - http:
          path: ${file(./env.yml):UserLoginPath}
          method: get
          authorizer:
            identitySource: method.request.header.email, method.request.header.birthday, method.request.header.password
            type: request
            name: authorizerLogin

  # Admin Functions
  listUsersByPlz:
    handler: handler/listUsersByPlz.listUsersByPlz
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
        Resource:
          - !Sub '${UsersTableLukas.Arn}/index/${file(./env.yml):Index_Name}'

  # Authorizer Functions
  tokenAuthorizer:
    handler: authorizer/tokenAuthorizer.authorizer
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - "Fn::GetAtt": [ UsersTableLukas, Arn ]
          - !Sub "${UsersTableLukas.Arn}/index/${file(./env.yml):Token_Index_Name}"

  authorizerLogin:
    handler: authorizer/loginAuthorizer.authorizer
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - "Fn::GetAtt": [ UsersTableLukas, Arn ]

  # Additional Functions
  logItemChanges:
    handler: handler/logItemChanges.logItemChanges
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ UsersTableLukas, StreamArn ]
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
        Resource:
          - "Fn::GetAtt": [ UsersTableLukas, Arn ]

resources: # CloudFormation template syntax from here on.
  Resources:
    UsersTableLukas: #must be same as TableName
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(./env.yml):Users_Table_Name}
        AttributeDefinitions:
          - AttributeName: ${file(./env.yml):Partition_Key} # email
            AttributeType: S # S = String, N would be for Number
          - AttributeName: ${file(./env.yml):Sort_Key} # Birthday as number for better filtering with key expression
            AttributeType: S # N for number, must be parsed from user inputed String in ISO 8601 format!!!
          - AttributeName: ${file(./env.yml):Partition_Key2} # Plz
            AttributeType: S # S = String, N would be for Number
          - AttributeName: ${file(./env.yml):Token_Partition_Key}
            AttributeType: S
        KeySchema:
          - AttributeName: ${file(./env.yml):Partition_Key}
            KeyType: HASH # primary key
          - AttributeName: ${file(./env.yml):Sort_Key}
            KeyType: RANGE # sort key
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${file(./env.yml):Index_Name}
            KeySchema:
              - AttributeName: ${file(./env.yml):Partition_Key2} # Plz
                KeyType: "HASH"
              - AttributeName: ${file(./env.yml):Sort_Key} # Birthday
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
          - IndexName: ${file(./env.yml):Token_Index_Name}
            KeySchema:
              - AttributeName: ${file(./env.yml):Token_Partition_Key} # Token
                KeyType: "HASH"
              - AttributeName: ${file(./env.yml):Token_Sort_Key} # Email
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline